from datetime import datetime, timezone
import traceback

import jwt

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

from app.database import engine, SessionLocal
from app import models
from app.config import settings
from app.routers import (
    auth,
    patients,
    samples,
    analysis,
    reports,
    access,
    users,
    audit
)


# ============================================================
# APPLICATION CORE
# ============================================================

app = FastAPI(
    title="METHYLOX",
    version="3.0.0",
    description=(
        "METHYLOX molecular intelligence platform "
        "with LIMS, analysis workflows, reporting "
        "and access control."
    )
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# HTTP AUDIT TRAIL
# ============================================================

@app.middleware("http")
async def audit_http_requests(request: Request, call_next):
    """
    Global HTTP audit middleware.

    Automatically records:

    - authenticated user_id
    - authenticated hospital_id
    - client IP
    - endpoint
    - HTTP method
    - HTTP status code
    - timestamp

    Business-level audit events such as:

    CREATE_USER
    UPDATE_USER
    ACTIVATE_USER
    DEACTIVATE_USER
    CHANGE_PASSWORD
    CREATE_PATIENT
    CREATE_SAMPLE
    CREATE_ANALYSIS
    GENERATE_REPORT
    ASSIGN_PERMISSION
    REVOKE_PERMISSION

    continue to be generated by their respective routers.

    HTTP_REQUEST is therefore the technical/request-level audit layer.
    """

    ignored_paths = {
        "/",
        "/docs",
        "/redoc",
        "/openapi.json",
        "/api/v1/health",
    }

    path = request.url.path

    if path.startswith("/api/v1/audit"):
        return await call_next(request)

    if path in ignored_paths:
        return await call_next(request)

    client_ip = None
    try:
        forwarded_for = request.headers.get("x-forwarded-for")
        if forwarded_for:
            client_ip = forwarded_for.split(",")[0].strip()
        elif request.client:
            client_ip = request.client.host
    except Exception as error:
        print("AUDIT IP WARNING:", str(error))

    user_id = None
    hospital_id = None
    try:
        authorization = request.headers.get("Authorization")
        if authorization and authorization.startswith("Bearer "):
            token = authorization.split(" ", 1)[1].strip()
            payload = jwt.decode(
                token,
                settings.SECRET_KEY,
                algorithms=[settings.ALGORITHM]
            )
            user_id = payload.get("id_user")
            hospital_id = payload.get("id_hospital")
    except jwt.ExpiredSignatureError:
        print("AUDIT JWT WARNING: token expired")
    except jwt.InvalidTokenError:
        print("AUDIT JWT WARNING: invalid token")
    except Exception as error:
        print("AUDIT JWT WARNING:", str(error))

    response = None
    status_code = 500

    try:
        response = await call_next(request)
        status_code = response.status_code
        return response
    except Exception as error:
        print("HTTP REQUEST ERROR:", str(error))
        traceback.print_exc()
        status_code = 500
        raise
    finally:
        db = SessionLocal()
        try:
            audit_log = models.AuditLog(
                user_id=user_id,
                hospital_id=hospital_id,
                action="HTTP_REQUEST",
                module="system",
                entity=path,
                changes={
                    "ip_address": client_ip,
                    "endpoint": path,
                    "http_method": request.method,
                    "status_code": status_code,
                },
                ip_address=client_ip,
                endpoint=path,
                http_method=request.method,
                status_code=status_code,
            )
            db.add(audit_log)
            db.commit()
        except Exception as error:
            db.rollback()
            print("===================================")
            print("HTTP AUDIT ERROR")
            print(str(error))
            traceback.print_exc()
            print("===================================")
        finally:
            db.close()


# ============================================================
# ROUTERS
# ============================================================

app.include_router(auth.router)
app.include_router(patients.router)
app.include_router(samples.router)
app.include_router(analysis.router)
app.include_router(reports.router)
app.include_router(access.router)
app.include_router(users.router)
app.include_router(audit.router)


# ============================================================
# DEBUG & UTILITY ENDPOINTS
# ============================================================

@app.get("/api/v1/debug/database")
def debug_database():
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version_num FROM alembic_version"))
        return {"alembic_version": [row[0] for row in result]}


@app.get("/api/v1/debug/patients-columns")
def debug_patients_columns():
    with engine.connect() as conn:
        result = conn.execute(text("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'patients'
            ORDER BY ordinal_position
        """))
        return {"columns": [row[0] for row in result]}


@app.get("/api/v1/debug/samples-columns")
def debug_samples_columns():
    with engine.connect() as conn:
        result = conn.execute(text("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'samples'
            ORDER BY ordinal_position
        """))
        return {"columns": [row[0] for row in result]}


@app.get("/api/v1/debug/create-default-hospital")
def create_default_hospital():
    db = SessionLocal()
    try:
        hospital = db.query(models.Hospital).filter(models.Hospital.id == 1).first()
        if hospital:
            return {"status": "already exists", "id": hospital.id}

        hospital = models.Hospital(id=1, name="Hospital Universitario")
        db.add(hospital)
        db.commit()
        return {"status": "created", "id": 1}
    finally:
        db.close()


@app.get("/api/v1/debug/fix-users-hospital")
def fix_users_hospital():
    db = SessionLocal()
    try:
        updated = db.query(models.User).filter(models.User.hospital_id == None).update({
            models.User.hospital_id: 1
        })
        db.commit()
        return {"status": "updated", "users_updated": updated}
    finally:
        db.close()


@app.get("/api/v1/debug/fix-patients-hospital")
def fix_patients_hospital():
    db = SessionLocal()
    try:
        updated = db.query(models.Patient).filter(models.Patient.hospital_id == None).update({
            models.Patient.hospital_id: 1
        })
        db.commit()
        return {"status": "updated", "patients_updated": updated}
    finally:
        db.close()


# ============================================================
# SYSTEM ENDPOINTS & ROOT
# ============================================================

@app.get("/api/v1/health", tags=["System"])
def health():
    return {
        "status": "ONLINE",
        "system": "METHYLOX",
        "version": "3.0.0",
        "timestamp": datetime.now(timezone.utc)
    }


@app.get("/")
def root():
    return {
        "system": "METHYLOX",
        "status": "running",
        "version": "3.0.0"
    }
